export const wikiditems = [
    {
        id: 1,
        title: "Réussite dans l'entrepreneuriat: un entrepreneur handicapé lance une start-up innovante",
        date: "1 Août 2024",
        content: "Un entrepreneur handicapé a lancé une start-up innovante qui connaît un grand succès, démontrant que la détermination et l'innovation peuvent surmonter les obstacles.",
        imageUrl: "https://via.placeholder.com/350x200",
    },
    {
        id: 2,
        title: "Un athlète handicapé remporte une médaille d'or aux Jeux Paralympiques",
        date: "5 Août 2024",
        content: "Un athlète handicapé a remporté une médaille d'or aux Jeux Paralympiques, inspirant de nombreuses personnes par son dévouement et son talent.",
        imageUrl: "https://via.placeholder.com/350x200",
    },
    {
        id: 3,
        title: "Succès académique: une étudiante sourde obtient un doctorat en physique",
        date: "10 Août 2024",
        content: "Une étudiante sourde a obtenu un doctorat en physique, prouvant que les limitations physiques ne peuvent pas empêcher les grandes réalisations académiques.",
        imageUrl: "https://via.placeholder.com/350x200",
    },
    {
        id: 4,
        title: "Un artiste aveugle expose ses œuvres dans une galerie renommée",
        date: "15 Août 2024",
        content: "Un artiste aveugle a réussi à exposer ses œuvres dans une galerie d'art renommée, montrant que la créativité et le talent transcendent les handicaps.",
        imageUrl: "https://via.placeholder.com/350x200",
    },
    {
        id: 5,
        title: "Lancement d'un livre inspirant par un auteur handicapé",
        date: "20 Août 2024",
        content: "Un auteur handicapé a publié un livre inspirant sur sa vie et ses réussites, offrant une perspective unique et motivante à ses lecteurs.",
        imageUrl: "https://via.placeholder.com/350x200",
    },
    {
        id: 6,
        title: "Réussite dans la technologie: un développeur en fauteuil roulant crée une application révolutionnaire",
        date: "25 Août 2024",
        content: "Un développeur en fauteuil roulant a créé une application révolutionnaire qui a transformé le marché, prouvant que les obstacles physiques ne peuvent freiner l'innovation technologique.",
        imageUrl: "https://via.placeholder.com/350x200",
    },
    {
        id: 7,
        title: "Un chef cuisinier handicapé ouvre un restaurant primé",
        date: "30 Août 2024",
        content: "Un chef cuisinier handicapé a ouvert un restaurant qui a remporté de nombreux prix, démontrant que le talent culinaire peut s'exprimer malgré les limitations physiques.",
        imageUrl: "https://via.placeholder.com/350x200",
    },
    {
        id: 8,
        title: "Un musicien handicapé enregistre un album à succès",
        date: "5 Septembre 2024",
        content: "Un musicien handicapé a enregistré un album qui a rencontré un grand succès, prouvant que la passion pour la musique peut surmonter tous les défis.",
        imageUrl: "https://via.placeholder.com/350x200",
    },
    {
        id: 9,
        title: "Une danseuse en fauteuil roulant performe sur une scène internationale",
        date: "10 Septembre 2024",
        content: "Une danseuse en fauteuil roulant a performé sur une scène internationale, inspirant des milliers de personnes par sa grâce et sa détermination.",
        imageUrl: "https://via.placeholder.com/350x200",
    },
    {
        id: 10,
        title: "Création d'une association par une personne handicapée pour soutenir d'autres personnes handicapées",
        date: "15 Septembre 2024",
        content: "Une personne handicapée a créé une association visant à soutenir d'autres personnes handicapées, offrant des ressources et une communauté d'entraide.",
        imageUrl: "https://via.placeholder.com/350x200",
    }
];
